-- MySQL Script generated by MySQL Workbench
-- Thu Feb 12 16:04:24 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinema` ;

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`cinema` ;

CREATE TABLE IF NOT EXISTS `cinema`.`cinema` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `street_name` VARCHAR(65) NOT NULL,
  `street_number` VARCHAR(12) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(12) NOT NULL,
  `country_code` CHAR(2) NOT NULL COMMENT 'ISO 3166-1 alpha-2 (\"CZ\", \"SK\")',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`screen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`screen` ;

CREATE TABLE IF NOT EXISTS `cinema`.`screen` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(12) NOT NULL,
  `capacity` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `description` TEXT NULL,
  `cinema_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_screen_cinema_idx` (`cinema_id` ASC) VISIBLE,
  CONSTRAINT `fk_screen_cinema`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `cinema`.`cinema` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`seat_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`seat_group` ;

CREATE TABLE IF NOT EXISTS `cinema`.`seat_group` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`seat` ;

CREATE TABLE IF NOT EXISTS `cinema`.`seat` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `row` VARCHAR(6) NOT NULL,
  `seat_number` TINYINT UNSIGNED NOT NULL,
  `screen_id` SMALLINT UNSIGNED NOT NULL,
  `seat_group_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_screen1_idx` (`screen_id` ASC) VISIBLE,
  INDEX `fk_seat_seat_group1_idx` (`seat_group_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_seat_idx` (`screen_id` ASC, `row` ASC, `seat_number` ASC) VISIBLE,
  CONSTRAINT `fk_seat_screen1`
    FOREIGN KEY (`screen_id`)
    REFERENCES `cinema`.`screen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seat_seat_group1`
    FOREIGN KEY (`seat_group_id`)
    REFERENCES `cinema`.`seat_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`seat_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`seat_attribute` ;

CREATE TABLE IF NOT EXISTS `cinema`.`seat_attribute` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`seat_feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`seat_feature` ;

CREATE TABLE IF NOT EXISTS `cinema`.`seat_feature` (
  `seat_id` MEDIUMINT UNSIGNED NOT NULL,
  `seat_attribute_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`seat_id`, `seat_attribute_id`),
  INDEX `fk_seat_feature_seat_attribute_idx` (`seat_attribute_id` ASC) VISIBLE,
  INDEX `fk_seat_feature_seat_idx` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_feature_seat`
    FOREIGN KEY (`seat_id`)
    REFERENCES `cinema`.`seat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seat_feature_seat_attribute`
    FOREIGN KEY (`seat_attribute_id`)
    REFERENCES `cinema`.`seat_attribute` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`event` ;

CREATE TABLE IF NOT EXISTS `cinema`.`event` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `runtime_minutes` SMALLINT UNSIGNED NOT NULL,
  `age_rating` VARCHAR(10) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`customer` ;

CREATE TABLE IF NOT EXISTS `cinema`.`customer` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL COMMENT 'password hash',
  `firstname` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`session` ;

CREATE TABLE IF NOT EXISTS `cinema`.`session` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `event_id` MEDIUMINT UNSIGNED NOT NULL,
  `screen_id` SMALLINT UNSIGNED NOT NULL,
  INDEX `fk_session_event_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_session_screen_idx` (`screen_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_dttm_screen_idx` (`start_time` ASC, `screen_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_show`
    FOREIGN KEY (`event_id`)
    REFERENCES `cinema`.`event` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_session_screen`
    FOREIGN KEY (`screen_id`)
    REFERENCES `cinema`.`screen` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`reservation` ;

CREATE TABLE IF NOT EXISTS `cinema`.`reservation` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total_price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `is_paid` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `session_id` MEDIUMINT UNSIGNED NOT NULL,
  `customer_id` MEDIUMINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_session_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_reservation_customer_idx` (`customer_id` ASC) INVISIBLE,
  CONSTRAINT `fk_reservation_session`
    FOREIGN KEY (`session_id`)
    REFERENCES `cinema`.`session` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_reservation_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cinema`.`customer` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`price_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`price_category` ;

CREATE TABLE IF NOT EXISTS `cinema`.`price_category` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`ticket` ;

CREATE TABLE IF NOT EXISTS `cinema`.`ticket` (
  `reservation_id` MEDIUMINT UNSIGNED NOT NULL,
  `seat_id` MEDIUMINT UNSIGNED NOT NULL,
  `price_category_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`reservation_id`, `seat_id`),
  INDEX `fk_ticket_seat_idx` (`seat_id` ASC) VISIBLE,
  INDEX `fk_ticket_reservation_idx` (`reservation_id` ASC) VISIBLE,
  INDEX `fk_ticket_price_category_idx` (`price_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_reservation`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `cinema`.`reservation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_seat`
    FOREIGN KEY (`seat_id`)
    REFERENCES `cinema`.`seat` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_ticket_price_category`
    FOREIGN KEY (`price_category_id`)
    REFERENCES `cinema`.`price_category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`price` ;

CREATE TABLE IF NOT EXISTS `cinema`.`price` (
  `session_id` MEDIUMINT UNSIGNED NOT NULL,
  `seat_group_id` SMALLINT UNSIGNED NOT NULL,
  `price_category_id` SMALLINT UNSIGNED NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`session_id`, `seat_group_id`, `price_category_id`),
  INDEX `fk_price_seat_group_idx` (`seat_group_id` ASC) VISIBLE,
  INDEX `fk_price_session_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_price_price_category_idx` (`price_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_price_has_session`
    FOREIGN KEY (`session_id`)
    REFERENCES `cinema`.`session` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_price_has_seat_group`
    FOREIGN KEY (`seat_group_id`)
    REFERENCES `cinema`.`seat_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_price_has_price_category`
    FOREIGN KEY (`price_category_id`)
    REFERENCES `cinema`.`price_category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
